### PR TITLE
fix: add warning when componentName is missing 

### LINKED ISSUE #1: Calling new-component with no arguments creates 'undefined' component
When running the command with no arguments, it creates a component named undefined.

```
ryan@tbp dev/proj (master) » new-component


✨  Creating the undefined component ✨


Directory:  src/components/undefined
Type:       class  functional  pure-class
=========================================


✓ Directory created.
✓ Component built and saved to disk.
✓ Index file built and saved to disk.


Component created! 🚀
Thanks for using new-component.


ryan@tbp dev/proj (master %) » git status
On branch master
Your branch is up-to-date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	src/components/undefined/

nothing added to commit but untracked files present (use "git add" to track)
ryan@tbp dev/proj (master %) »
```

### PR DESCRIPTION
**Pull request by morajabi**
Great project @joshwcomeau! it's my problem too, so I wanted to help with that. Well done!

fixes #1

### CODE REVIEW

**Comment by joshwcomeau** [comment]
yay :D Thanks @morajabi! Really appreciate your work on this.

**Comment by morajabi** [comment]
Oh! Thanks for adding me as a collaborator! I really appreciate it too. I hope I can add something worthy.

**Comment by joshwcomeau** [comment]
@morajabi You beat me to it! I was just writing up some info about that :)

I've found that adding enthusiastic, competent community members as collaborators has been really awesome for the open-source projects I've been involved with. Your general enthusiasm for this project (discussing #2 and providing this PR) more than qualify you!

Collaborators have full write access, so my only request is that you don't commit directly to master, and at least 1 other collaborator (for now, that's just me!) has reviewed code before it's merged in. But yeah, if I or any future collaborators open PRs, feel free to review/merge :)

Of course, accepting the invitation doesn't mean you *have* to do anything :) feel free to do as much or as little as you want. I'm about to open some issues for adding support for different styling solutions, and so your work with `styled-media-query` might mean you're interested in adding `styled-components` support? Will link to that issue when its open

**Comment by morajabi** [comment]
Thank you, Josh! You mentioned good points.

> so my only request is that you don't commit directly to master, and at least 1 other collaborator (for now, that's just me!) has reviewed code before it's merged in. 
I'm aware of that, so why don't you make it protected to avoid any unwanted damage?

> Of course, accepting the invitation doesn't mean you have to do anything :) feel free to do as much or as little as you want.
I like your awesome work here (as I said on Twitter) and It makes me happy to contribute to something useful in the community that I love :)

> I'm about to open some issues for adding support for different styling solutions, and so your work with styled-media-query might mean you're interested in adding styled-components support?

OK, no problem with that, actually now I'm a member of SC and I'm working on the main [styled-component website](https://github.com/styled-components/styled-components-website/issues/83) too.

**Comment by joshwcomeau** [comment]
> I'm aware of that, so why don't you make it protected to avoid any unwanted damage?

Huh, wasn't aware you could do such a thing! Thanks for the tip, just went digging through the settings and they're surprisingly powerful.

> I'm a member of SC and I'm working on the main styled-component website too.

Congrats :D

**Comment by morajabi** [comment]
> Congrats :D

Thanks :)

**Pull request merged**
